### ISSUE TITLE
Support keepWhitespace on completions / specify default behaviour

### ISSUE THREAD

**Issue by DanTup** [microsoft/language-server-protocol#880] opened 2019-12-19 10:08 UTC
VS Code has a `keepWhitespace` property on `CompletionItem`s that prevents VS Code from messing with the whitespace provided by a language server (by default, Code assumes language servers do not correctly take indenting into account).

As far as I can tell, LSP doesn't have this, nor is it explicit about whether editors should/should rewrite edits to account for indenting. This seems like something that should be explicitly specified (especially since IMO VS Code's default behaviour is surprising from a language server perspective).

**Comment by rcjsuen** [comment] 2019-12-19 11:31
@DanTup Oh, this ain't our first rodeo. Enjoy reading up on #83. :P

**Comment by DanTup** [comment] 2019-12-19 11:40
Oh joy :-)

Well, it seems like there was progress anyway - in November last year VS code added a boolean for it (https://github.com/microsoft/vscode/issues/57093#issuecomment-433961972). I believe all it needs is exposing in LSP (and the default behaviour - which I still think is nuts - to be clarified).

I'm trying to migrate Dart over to LSP, but right now it would re-introduce a bunch of bugs we've already previously fixed for non-LSP which doesn't seem like a great sell ☹️

**Comment by dbaeumer** [comment] 2019-12-20 15:43
I marking it as a dup of #83. I will add it to the next release. The problem is that in LSP for this there was some pushback to simply copy the VS Code boolean.

**Closed by dbaeumer** 2019-12-20 15:44 UTC

**Comment by DanTup** [comment] 2019-12-20 16:29
> The problem is that in LSP for this there was some pushback to simply copy the VS Code boolean.

Understood - though it seems to be working for VS Code and a boolean that lets us fix this is better than longer delays IMO. If it turns out to be insufficient, it can be replaced with something better in the same way as other changes are made (LSP seems fairly reasonable at handling changes like this, and being backwards compatible).

I have no preference for what the fix is, as long as it's *possible* to disable this. It's been a frustrating bug for years, and it was finally fixed in VS Code. Having to delay LSP migration further, or having to re-introduce the same bug would be a real shame 😔
