### ISSUE TITLE
The specification doesn't denote a way for a server to 'close' a signature help request

### ISSUE THREAD

**Issue by bhelyer** [Microsoft/language-server-protocol#496] opened 2018-06-14 07:10 UTC
What should servers return in response to a `textDocument/signatureHelp` request to mark it as done? Say you have a function `add` that takes two arguments, once the user has finished writing the call, the hovered documentation should disappear -- the C++ extension does this when the closing paren is written, for example.

But no matter what I send back, vscode leaves the signature hover up, highlighting the last parameter. Null results, an empty `signatures` list, a `$/cancelRequest`, nothing seems to have any effect. The only way to make it disappear is by hitting escape.

Am I missing something obvious, or is there a way in the spec to achieve what I want?

**Comment by dbaeumer** [comment] 2018-06-14 08:14
Actually returning nothing (`null`) should close it. Agree that this is missing in the spec. Which client are you using?

**Comment by bhelyer** [comment] 2018-06-14 09:31
I am using Visual Studio Code. 

When you say nothing, do you mean `..."result":null...` as the response? If that's the case, that's what I *though* I was doing, but it's likely a bug on my end (doing a bit of refactoring of our server code) . When I get back to work next week, I'll double check that though. If it turns out not to be our bug, I'll see if I can't get a simple repro for y'all.

**Comment by bhelyer** [comment] 2018-06-24 03:42
So I eventually got around to looking at this. VSCode will indeed close the signature help on result:null (I wasn't hooking into every event I needed, namely ')') but it felt very 'inconsistent' -- I figured out why. The `textDocument/didChange` notification for the ')' is sometimes coming in after the signatureHelp request. I understand that these things aren't strictly ordered, but this is rather frustrating behaviour, and I'm not entirely sure the best way of handling it (our server's completion is mostly single threaded).  AFAICT, the only real way to handle this is to set non textChange notifications aside for a few milliseconds, to see if the completion event was sent simultaneously with a change (else the completion code can have no way to know it's looking at `add(1, 2)` and not `add(1, 2`, and once that response has been sent, it's too late).

This is all a bit off topic, so I apologise.

**Comment by bhelyer** [comment] 2018-06-26 11:10
Sorry for the spam, but I just wrote some code that flips change and signatureHelp requests when appropriate, and I'm looking at the logs, and despite replying

```
{"jsonrpc":"2.0","id":20"result":null}
```

to the request

```
{"jsonrpc":"2.0","id":20,"method":"textDocument/signatureHelp","params":{"textDocument":{"uri":"file:///d%3A/F/Code/volt64/Test/src/main.volt"},"position":{"line":9,"character":10}}}
```

The signature help window remains open. I need to investigate further, but it seems it is not as simple as returning nothing to the request, or vscode has a bug (pending me missing something else, of course).

**Comment by rcjsuen** [comment] 2018-06-26 16:03
@bhelyer Your suggestion of changing `textDocument/signatureHelp` to include the character that triggered it is reasonable. It's similar to what was done for `textDocument/completion` in #138.

**Comment by dbaeumer** [comment] 2018-07-24 14:34
Actually this is currently controlable. The `signatureHelpProvider` property of the server capabilities allows you to specify signature help trigger characters.

In response to the ')' insert. This is an auto inserted character and a server should not rely on the client doing this. Nor can it rely on when this will occur. IMO the interesting character for signature help is '('

OK to close or do you specify both '(' and ')' as trigger characters?

**Comment by bhelyer** [comment] 2018-07-25 00:47
@dbaeumer I've hooked into `)`, but the `textDocument/signatureHelp` signal can occur before the `didChange` notification allows the server to see it -- so there's no way to tell for sure what the trigger character for a given `textDocument/signatureHelp` is -- consider the following scenario:

    add(1, foo

That's the state of the document when we get the `signatureHelp` request. Say we have '(', ',' and ')' as trigger characters. If the user has hit ',' we may set another signature as active. If the user has hit '(', we have to lookup 'foo' and find its signature. If the user has hit ')' we have to send an empty request to close the signature request. If we can't rely on the change event occurring before the signatureHelp request, as you say, there is *no* way to figure this out cleanly with the current protocol. We can only respond to a given request once, so having the correct trigger character is important, at least in the way our server is architected.

Now in our own server, [I've worked around this with a somewhat ugly solution](https://github.com/VoltLang/Volta/blob/vls/vls/src/vls/messageHopper.volt). But really, the cleanest solution in my mind is to just put the trigger character somewhere on the `signatureHelp` request.

Also, I don't understand what you mean by ')' is an 'auto inserted character'. That's not necessarily true, is it? It certainly isn't in our server.

**Comment by Gama11** [comment] 2018-07-25 09:32
There are plans to add context information to signature help requests, just like there is for regular completion: https://github.com/Microsoft/vscode/issues/34737. Once this is added to VSCode, it will hopefully make it into the LSP as well.

For completion, it looks like this:

https://github.com/Microsoft/vscode-languageserver-node/blob/5f9c993ff38f5c369949aeb359b3e9b178172dbc/protocol/src/protocol.ts#L1389-L1403

**Comment by dbaeumer** [comment] 2018-08-21 19:52
@bhelyer there is a misunderstanding: if the user types ')' the signature help request should come after the user has typed the ')'. If not, please provide steps on how to reproduce and then I will certainly investigate. Things a different with auto closing brackets. For example some editors might auto insert a closing ')' when the user types '('. If '(' triggers signature help it might happen that the request is send before the closing ')' is inserted. But this shouldn't influence the result anyways.

**Comment by bhelyer** [comment] 2018-08-22 01:48
That's definitely the behaviour I'm seeing. To be precise, the user types ')', the signature help request is sent, and then the file change event for ')' is sent. If I can find some time over the weekend, I'll try and make a simple example.

**Comment by dbaeumer** [comment] 2018-08-23 14:51
@bhelyer great.

**Closed** 2018-08-30 15:01 UTC
Labels: needs more info

**Comment by dbaeumer** [comment] 2018-09-07 11:05
@bhelyer please ping if you have steps. Then I will reopen the issue.
