### ISSUE TITLE
Alternate forms for WorkspaceEdit

### ISSUE THREAD

**Issue by alanz** [Microsoft/language-server-protocol#224] opened 2017-04-21 16:16 UTC
At the moment a `WorkspaceEdit` is composed from `TextEdit`s

Some tools generate output in the form of a diff

Perhaps instead if accepting only `TextEdit`, some type capturing a diff could also be used.

**Comment by kdvolder** [comment] 2017-04-24 15:36
I.m.o we shouldn't complicate the LSP spec with this. Maybe rather looking for, or creating, some kind of a library or tool to parse / convert diff format independently is a better option.

**Comment by alanz** [comment] 2017-04-24 15:44
Yes, I nearly deleted this issue shortly after creating it as I thought about it a bit more, for that reason.

But then there should be a single "change" concept, at the moment there are two, a `TextEdit` and a `TextDocumentContentChangeEvent`, one going server to client, the other client to server.

**Comment by dbaeumer** [comment] 2017-05-17 11:57
The reason for having two is that the first is signaling events about what happened on the client side. These evens (changes) need to be applied in the order in which they appear. There is not need for the server to do any position magic.

Same with TextEdits: they describe how a document is moved from version n -> n+1 using positions of version n. In both cases it makes the live of a server easier. No need for a server to do any position magic. 

I will close the issue since this is basically by design to ease the server implementation.

**Closed by dbaeumer** 2017-05-17 11:57 UTC
