### ISSUE TITLE
Can a DocumentFilter also be a string?

### ISSUE THREAD

**Issue by rwols** [microsoft/language-server-protocol#1127] opened 2020-11-05 10:48 UTC
The spec tells me that a DocumentSelector is a list of DocumentFilters. A [DocumentFilter](https://microsoft.github.io/language-server-protocol/specification#documentFilter) is an object that may contain `language`, `scheme` and `pattern` keys.

But the [implementation](https://github.com/microsoft/vscode-languageserver-node/blob/e3d3314932ea92fbc175d96c400f7ac9ae81985b/protocol/src/common/protocol.ts#L118-L118) in vscode-language-server-node defines DocumentFilter as either object or a string.

For practical purposes, we should probably update the spec to allow a plain languageId as DocumentFilter because the vue language server is now already depending on this behavior.

**Comment by rchl** [comment] 2020-11-05 11:21
Just a note that even though the latest Vetur release (0.29.0) is using a string value, it's actually a bug and doesn't work in VSCode even. I'm fixing it in https://github.com/vuejs/vetur/pull/2436. So Vetur doesn't depend on that behavior, it's just broken.

Also, note that I've created an issue about those types on https://github.com/microsoft/vscode-languageserver-node/issues/685

**Comment by dbaeumer** [comment] 2020-11-05 12:26
Actually we supported a string at the beginning but the problem is that users should think about the scheme. If they only pass in a string then they get the document for all schemes. This is why the spec only support document filter. See the comment in the implementation. So I will close the issue.

**Closed by dbaeumer** 2020-11-05 12:26 UTC
