### ISSUE TITLE
PublishDiagnostics Notification and File Deletions

### ISSUE THREAD

**Issue by cdietrich** [Microsoft/language-server-protocol#463] opened 2018-04-25 11:03 UTC
if the client deletes a file is the server then required to send a empty PublishDiagnostics Notification to clear the issues? at least vscode does not seem to clear the issues for deleted resources.

**Comment by cdietrich** [comment] 2018-04-25 11:14
<img width="1033" alt="bildschirmfoto 2018-04-25 um 13 12 19" src="https://user-images.githubusercontent.com/238736/39242456-5be4a04e-488a-11e8-97ee-755a9cb76aed.png">

sample from vscode after deleting c.mydsl (server receives did change watched files and removed the file from its structure but did not send and empty notification.

=> Bug in vscode or should the server have sent an empty notification for the deleted file

**Comment by rcjsuen** [comment] 2018-04-25 11:28
According to the [specification](https://microsoft.github.io/language-server-protocol/specification#textDocument_publishDiagnostics)...

> Diagnostics are “owned” by the server so it is the server’s responsibility to clear them if necessary.

This has been brought up in other VS Code extensions in the past. See Microsoft/vscode-docker#237 and ionide/ionide-vscode-fsharp#730.

Although it does seem to me like clients should just wipe these things out themselves. Especially in the case where the client initiated the deletion (and you didn't popup an external terminal and called `rm Errors.java` yourself externally).

What does everyone else think?

**Comment by cdietrich** [comment] 2018-04-25 11:58
no i used the normal delete file context menu in vscode.

@mickaelistria how does lsp4e treat this situation? at least in eclipse you cannot show resource markers for files that are not there anymore

**Comment by mickaelistria** [comment] 2018-04-25 13:30
For LSP4E and Eclipse IDE in general, it's just impossible by design of the marker API to create or keep a marker for a file that doesn't exist, so removing a file does remove automatically all markers.
This behavior is deep in the roots of markers in Eclipse Platform, and even if server sends different signals, it's not something we can implement a-la VSCode. The closest thing for LSP4E to replicate a similar behavior would be to placed diagnostics for deleted files as markers on the closest parent folder, but I don't think it'd be a good thing as no-one complains about it in LSP4E while 3 people already complained about VSCode appraoch.
I believe the issue you report is more specific to VSCode allowing such inconsistent state of markers, not something that's a bug in LSP.

**Comment by cdietrich** [comment] 2018-04-26 05:52
no i mean it the other way round: what happens if in lsp4e the server reports issues for files that do no exist: does it give a framework error in lsp4e

**Comment by mickaelistria** [comment] 2018-04-26 07:05
If LSP4E receives diagnostics on files that don't exist, those are just
ignored:
http://git.eclipse.org/c/lsp4e/lsp4e.git/tree/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/diagnostics/LSPDiagnosticsToMarkers.java#n66
. I don't think we'll change this behavior in LSP4E unless there are valid
user-stories to suppor it.

**Comment by dbaeumer** [comment] 2018-04-26 14:03
To make things consistent in all cases we decided to make the creator of markers responsible for their deletions. Since the marker were created my the server he owns them and needs to wipe them.

Unless I see a compelling case to change this I opt to close this issue. The current design is easy to communicate since it has no exceptions.

**Closed** 2018-04-26 14:08 UTC
Labels: needs more info
