### ISSUE TITLE
Clarify magic indentation fixes applied to multi-line text edits in CompletionItem

### ISSUE THREAD

**Issue by kdvolder** [microsoft/language-server-protocol#83] opened 2016-10-05 01:21 UTC
It looks like when I create a completion item which contains newlines, so expands to more than one line of actual text... vscode applies some kind of magic indentation fixes to my edit (rather than taking my edit at face value and replacing my text exactly as given).

This is disturbing really because my 'newText' already contains exactly the needed spaces to get the desired/correct indentation. I'm seeing that in vscode additional spaces are added on top of that which actually messes things up.

E.g my language server sends a completion like this:

```
  {
       "label":"services",
       "kind":5,
       "sortText":"00014",
       "filterText":"services",
       "textEdit": {
            "range":{
                  "start":{"line":2,"character":4},
                  "end":{"line":2,"character":4}
       },
      "newText":"services:\n      - "
 }
```

There are precisely 4 spaces between the `\n` and the `-`.

However, when the completion is invoked it looks like 8 spaces get added into the document instead.

Really, I'd prefer if 'newText' doesn't get subjected to this kind of magic stuff. But if there is indeed magic stuff happening, then we probably should have clear descriptions in the LS spec to explain exactly what magics to expect.

PS: This is somewhat related to #82 (both issues concern a different kind of undocumented 'magic interpretation' applied to the contents of the TextEdit's`newText` field).

**Comment by dbaeumer** [comment] 2016-12-30 11:31
@jrieken can you please comment. Is there a way to avoid the formatting (e.g. by using the new range property ?)

**Comment by dbaeumer** [comment] 2016-12-30 11:31
Moving to January. Need to first understand what exactly is happening and then need to think about a spec.

**Comment by jrieken** [comment] 2016-12-30 11:51
The *magic* is that VS Code prefixes new lines in snippets and completions with the [indentation](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/common/snippet.ts#L100) of the 'reference line', that is the line on which the operation was started. So, if your reference line is indented with 4 spaces each new line in your snippet in prefixed with 4 spaces. This is in line with other editors and makes it easy to create snippets and completions without  always checking the indentation properties of the current document.

**Comment by kdvolder** [comment] 2017-01-13 17:54
Cool, okay. That clarifies it.

I think it it would be convenient if there was a way to enable/disable this magic, maybe by adding a boolean field 'enableMagicIndent' or something like that to the CompletionItem (or to the list to avoid repeating it for every item). To preserve backwards compatibility this field could be optional and the magic indent could be enabled by default if the field is absent.

**Comment by kdvolder** [comment] 2017-01-13 18:10
> Cool, okay. That clarifies it.

Actually... just a little more nitpicking. I am wondering... how does cursor position (before edit) play into this?

For example, let's say that cursor is shown as `<*>` and we have this in the editor prior to applying the edit:

```
   <*>   foo
```

I.e. there are 3 spaces in front of the cursor and 3 spaces after the cursor. The reference line is indented by 6 spaces (first-non-whitepace char is the 'f' from foo which is preceded by 6 spaces). 

It would seem most logical to me that the here 'magic indent' in this case should be 3 spaces rather than 6 (i.e the text after the cursor is not considered). But the simple phrasing of the magic rule as given by @jrieken, I think above would imply its actually 6 spaces.

**Comment by kdvolder** [comment] 2017-04-18 23:08
I'm going to re-iterate my request to disable the 'magic indents'. I'm doing an editor for yml, which is very finicky around proper indentation levels (the indentations have semantic meaning!). I'm finding the magics are making it impossible in some cases to implement the correct/desired behavior. 

Here is a concrete example (cursor position is shown by `<*>`)

```yml
resources:
- name: source-repo
  type: 
    <*>
```

Invoking content assist is supposed to expand into this (where the `$1`, `$2` and `$3` are tabstops in a snippet)

```yml
resources:
- name: source-repo
  type: 
    pool
  source:
    uri: $1
    branch: $2
    pool: $3
```

Unfortunately this is not possible because the insertText with 'magic indents' applied will always end up indented *more* than the reference indent (i.e. indentation of `pool`).  Its not possible to communicate the intent to apply a negative relative indent to `source`.

So can we please, please, please add a switch to the protocol that allows to turn this magic off?

**Comment by kdvolder** [comment] 2017-04-18 23:21
Afterthought... It occurred to me that maybe this:

>  Its not possible to communicate the intent to apply a negative relative indent

Might not be true. Maybe a `\b` (backspace) character which is kind of a negative space could be added to the front of a line to communicate this intent.

Alas... doing that with vscode's client just inserts the control characters into the editor text (which has some mildly confusing effects).

**Comment by dbaeumer** [comment] 2017-05-17 14:17
Moving to 4.0 to consider the capability PR.

**Comment by dbaeumer** [comment] 2017-05-17 14:18
We should first clarify the current behavior.

**Comment by kdvolder** [comment] 2017-05-17 18:35
> We should first clarify the current behavior.

I tried to do that in the PR as well. Though the explanation is part of the capability description.

My apologies for taking so long with the CLA. When I have to ask permission from legal, things tend to get annoyingly complicated. If you think there's a good chance you'll accept the PR for 4.0 (?). I'll prioritize the paper work I have to do for this. So let me know how you feel about the chances for this PR if you can.

**Comment by dbaeumer** [comment] 2017-05-18 08:50
I think we need to do two steps:

- clarify the current behavior
- allow in 4.0 to control the behavior. 

If you don't sign the CLA it will now mean that the feature request is dropped :-)

**Comment by mickaelistria** [comment] 2018-06-01 06:57
To me, this is not a bug in LSP, but a bug in VSCode.
The documentation nowhere says anything about such extra-indentation, and just says that the TextEdit are expected to apply from last to first. As such, VSCode interpretation of TextEdit is over-doing work with VSCode specific choices, but this is not really because of protocol.
If the same thing were done with Eclipse LSP4E because of some additional handling of editorconfig, it would more likely be seen as a bug in LSP4E.

VSCode-based language servers may decide to read some extra configuration files to apply some indent, but those should be internally and reflected in the TextEdit.

So instead of tweaking the protocol or adding more clarification or more complexity by allowing multiple cases, what about just fixing VSCode? (You'll see I'm placing a major bait for troll about governance and vendor-neutrality here, but I think it can be useful to discuss it at some point and this bug is a great example)

**Comment by kdvolder** [comment] 2018-06-04 17:21
I am also in favour of 'fixing' vscode not to do these magical indents. I didn't really want them in the first place and it is a bit of hassle for us to actually 'undo' the magic indents, because our completion engine already creates properly indenting edits. It's also a bit of hassle in the sense that we are dealing with this by passing commandline switches to our ls on launch to enable / disable this 'undo magic indents' for vscode but not for other clients.

**Comment by dbaeumer** [comment] 2018-06-06 09:10
The major reason why we added this behavior to VS Code is to simplify the creation of these edits for the language provider. Otherwise a provide needs to due the following

- compute the indent by itself
- using the right indentation characters (tab versus space, mixed, ...)

So it is not simply about removing the behavior. We would also need to think how we best communicate at least the second to the server and ensure that servers do the right thing here. Not sure if this makes live easier.

**Comment by dbaeumer** [comment] 2018-06-06 09:21
And then there is the formatter issue (may be not for code complate for refactorings). If I for example would run a extract method refactoring I would expect that the inserted code honors my formatter settings. So it might not be the best think to force the servers to honor this. It would IMO be better that a server can request this from the client. 

I do agree that this must be clearly speced and should be implementable for all clients. But as said in the previous post it is IMO not the right approach to push this all onto the server.

**Comment by kdvolder** [comment] 2018-06-06 15:45
@dbaeumer I see your point. Those are good arguments for keeping the indenting responsibility on the client. 

And though I can't speek for the general case, but in my use-case the magic indents are totally unwanted. Accounting for the magics that will applied by the client and somehow making sure that the edits the server sends + the magic indents add up to being correct is just more complex than just computing the correct indents on the server side. There are even some cases that cannot be correctly implemented at all because it would require a negative relative indent (which is not possible if the client allways adds some set amount of space in front of the edits). 

Since yaml doesn't even allow using tabs, I guess the complication of the server needing to know whether it should use tabs or not isn't present here.

Even if my case isn't perhaps the 'general' case. At least it shows that not all server will want or be able to work with these magics as vscode currently applies them. So at the very least they should be optional. 

As to whether we should have these magics at all. My thoughts are that it seems rather complex to describe the exact magics (or possibly even to simply get everyone to agree what kind of magics actually makes sense across all language servers and clients).

I think those complexities probably outweigh issues with tabs and spaces in multi-line completions. But this is just my feeling on it. (I.e. if a client wanted to, maybe it could do automatic tabs <-> spaces conversion after inserting an edit, but without actually changing any indentation levels, and we could make server side easier by stipulating they are free to only use spaces and rely on client to convert spaces to tabs according to user preferences)

**Comment by kdvolder** [comment] 2018-06-06 17:27
One more response 

> I would expect that the inserted code honors my formatter settings. So it might not be the best think to force the servers to honor this. It would IMO be better that a server can request this from the client.

You are assuming the client actually knows how to properly format the code. But is that even a valid assumption? For example, does vscode lsp client know how to format Java code according to the user's preferences? Or is code formatting really also in the domain of the language server.

**Comment by dbaeumer** [comment] 2018-06-07 12:45
@kdvolder thanks a lot for the feedback. I agree that for YAML my points to not really count however I would like to find a solution that works across servers and languages. 

> You are assuming the client actually knows how to properly format the code. 

Yes. The idea is that the client knows the language mode of the file modified and whether there is a formatter for it or not.

From my past experience (implementing the refactoring engine for Eclipse and quite some Java refactorings) a model that worked IMO is as follows:

- formatters only touch white spaces (is given for most of them) 
- refactorings, source and code actions should touch the least amount of white space characters as possible to leave existing formatting untouched. 
- if new code needs to be inserted it should be run through the formatter before inserting it. We did this in all Eclipse Java refactorings and source actions. However we had a Java formatter that was able to format partial code by telling it a starting node type and a initial indent (e.g. format the text and assume that the first node is a type declaration node and start with an indent of two).

I haven't thought about how to best make this nice in the LSP. So any ideas here are welcome. 

And I do fully agree that such a support should be optional and controllable by the server.

**Comment by kdvolder** [comment] 2018-06-07 16:33
> to find a solution that works across servers and languages

I guess this is really my point here. The current solution doesn't as it is clearly unwanted for at least some servers.

Letting the server do the formatting, while perhaps a bit harder on server implementor at least has two advantages:

1. It doesn't add complexity to the protocol spec and client implementors.
2. It doesn't frustrate (or even prevent!) server implementors from implementing completion that have the desired effect on the clientside, for languages where white space has semantic meaning (yaml is an example but there are others, for example Python).

@dbaeumer I do beleave you know what you are talking about from past experience, but I think maybe the experience comes from languages where whitespace carries no semantic meaning. So perhaps it isn't as annoying when the whitespace gets rearranged in a somewhat unpredictable/uncontrollable way.

Anyhow... here's a proposal on moving forward that hopefully gets us out of the current impasse.

1. We shouldn't add this 'magic indent' logics to the spec at this time because I don't think that there is agreement how or even if it should even be there.

2. vscode should fix its implementation so it follows what the spec says (i.e. no magic indentation)

3. At a later time, proponents of magic indentation can propose to add something to the spec that allows servers to 'opt in' to magic indents. The proponents can work out the details of how this should be spec-ed and implemented at a later time.

Why I think this is the right way to move ahead:

1. Vscode will actually implement what the spec currently says, and behave the same as other clients who simply read the spec and implemented what it says.

2. Server implementors get control over how their edits are indented. (As should be clear by now, not all servers will want how vscode does this now. But if a server did really want the magic indent exactly as vscode currently implements it, they can implement it relatively easily themselves (the magic indent logic is just some fairly simple copying of whitespace from the cursor's line, it's really nothing fancy, and just a few lines of code).

3. If we agree that just adding vscode current implementation into the spec is not the right thing to do. Making this a 'opt-in' feature to be added at a later time, at least resolves the current impasse and doesn't block for a long period of time, pending a successful agreement on how exactly these magics should be specced and implemented.

**Comment by mickaelistria** [comment] 2018-06-08 09:14
Does VSCode assume that editor has to indent when applying any TextEdit from whatever message, or is it a specific case of completion?
Also, would we want the behavior to be always the same for a given LS instance?
Basically, I'm wondering whether we could introduce a flag `requireIndent` or `requireFormat` in `TextEdit` directly so clients would always be expected to look at it to perform extra formatting.

**Comment by dbaeumer** [comment] 2018-06-08 09:29
I do agree that if white space matters in a language this is best controllable by the server. Otherwise the formatter would need some semantic hint which will very likely be hard to spec and control.

I do like the idea of starting with the minimum (which is no smartness) and then adding additional behavior later on. If we do that hard it will break all existing servers which do expect the smart indent to happen although I agree it is not speced that way. So I would opt to have at least a capability to control this or we need to do a pull to find out how many people rely on this. 

Regarding the formatter: even if the LS provides a formatter it might not be the one configured in the client. IMO the only part in the picture here is the client that knows how to format code even if it delegates this back to the server.

**Comment by kdvolder** [comment] 2018-06-08 15:40
>  If we do that hard it will break all existing servers

True in as far as the servers care about whitespace.

For example our server will be broken by this. But the fix is easy since the 'undo magic indent' processing is enabled by a commandline switch specific for launching our server with vscode (if we didn't have the switch our server would be broken on other clients). So all we have to do is remove that switch. (And we can then also go ahead and delete a bunch of finicky code that deals with the magic as well).

I don't know about other servers, but I suppose if they really relied on these magics, then it means these servers are already broken on other clients than vscode. This will just make them break on vscode in the same way, and... fixing that problem has an added bonus that it also fixes them for other clients.

Also... I think vscode-extension packages can easily control when they update to a new client version via their package.json file. So... they are not forced to fix / deal with these problems until they choose to adopt a new client version.

All in all I think this is the better option.

I could offer some thoughts on how magic indents should work when they are added back, but really... these details do not concern me. If there's an on/off switch I'd be happy and I don't particularly care how it would work when it is turned on since I won't be turning it on.

As to how to turn it on / off. I think there are a few different approaches. Either a server capability (would work for us) or a flag in the text edit (if servers need more fine grained control). One case to consider is that some language servers might be serving more than one language. So it is not unlikely that a server-wide switch isn't good enough.

There is also a questuon about whether additonal edits also should be subjected to magic indent. Or does it only apply to the main edit? I'm not even sure if vscode only applies these fixes to main edit or to all edits alike. 

Again... I think all these details, including those around how to 'opt in' should probably be worked out later. So this ticket can be closed *now* with vscode simply implementing the current spec. And people who really care about having these magics can work out the details, while those of us who don't want them can get on with implementing features in their language servers instead of continuing to argue about the details.

**Comment by kdvolder** [comment] 2018-06-08 15:47
>  So it is not unlikely that a server-wide switch isn't good enough.
Actually come to think of it. Our ls also has a few completions that return code templates in a .java context. And it might actually be beneficial there to not to have to worry about the tabs versus spaces issue. In other words, there might just be a case here where our LS turns this off for some completions (yaml context) and on for others (java context).

**Comment by kdvolder** [comment] 2018-06-20 15:47
@dbaeumer Thanks for the update. That actually sounds good. 

But I will re-iterate my suggestion to split this issue (and its resolution) into two separate issues/steps for the short versus long term goals.

Step 1: resolve the current issue by making vscode 'comply' with the spec as it is currently written.
Step 2: add a 'opt in' feature to the spec to do all the things you suggested above.

I propose to do it this way because 

1. Working out all the details of how this should work in step 2 sounds complex and could take a long time. So why should we wait for the completion of this process to fix the short term pains caused by vscode currently not working the same as other implementors of the spec.
2. Personally I don't wish/need to be involved in shaping the details in step 2, because I really don't care how it works. (I just want to have it turned off. So how it works if turned on matters very little to me. And naturally I also don't have useful insights on how it should work).

**Comment by kdvolder** [comment] 2018-06-20 15:48
> We can debate the default for the LSP.

It should be obvious where I stand on this. It should be turned off by default to comply with the spec in a backwards compatible way, as the spec is currently written.

**Comment by dbaeumer** [comment] 2018-06-21 08:41
I see your point and if we would start on a green field I would exactly do that. But there might be language server out there unknowingly relying on the behavior and if we change this in the VS Code client implementation I am of the opinion that I should at least offer them a way to opt into the old behavior if I do break them. Otherwise I will have more customers that complain than right now :-)

I always tried to not break users if possible. So even implementing the short term goal needs some engineering effort.

**Comment by kdvolder** [comment] 2018-06-21 16:02
> I am of the opinion that I should at least offer them a way to opt into the old behavior if I do break them.

Fair enough. But don't they already have an easy option? Namely simply not upgrade to a newer version of the lsp client for vscode?

**Comment by dbaeumer** [comment] 2018-06-21 21:14
Yes, that is a good point but it would require that we release 5.x and they would be cut of from new features until we added the support. I am usually not back porting new features to old releases.

**Comment by kdvolder** [comment] 2018-07-19 17:46
Well, FWIW, you are doing exactly what I feared: leaving this unresolved for a long time, and doing nothing while thinking about a better solution than just removing it and making it an optional feature to be added and specced properly later.

In the mean time the confusion around this is a continuing PITA for us... and actually getting worse. It seems that atom folks now decided it was a good idea to try to emulate vscode's 'magic indents' behavior even though it isn't part of the spec.

Unfortunately, and unsurprisingly (given that the behavior isn't documented or specced) they have implemented it differently than vscode so it behaves different for some edge cases. This is realy unfortunate because now, if we want to have our servers work properly with vscode and atom and eclipse, we need three different implementations of 'magic indent aware completion post-processor'.

Really, do you need more arguments that this feature should simply be removed for now?

**Comment by dbaeumer** [comment] 2018-07-24 14:20
As I was trying to explain before this will might break existing VS Code extension (even if not clearly speced) so I am of the opinion that we need to offer extension relying on this right now a way to reserve their behaviour. I will make sure that this gets added to our road map plan so that we can plan it in.

**Comment by kdvolder** [comment] 2018-07-24 16:36
> As I was trying to explain before this will might break existing VS Code extension

I get that, but as I already pointed out:  if there are extensions that will break (we don't know that there are), they will *only* break on vscode if they update to a newer vscode-client version. So they already have a way to 'reserve their behavior'.

Anyhow. I guess there is really not much point in pressing it further. I trust it will eventually get sorted out... somehow.

**Comment by dbaeumer** [comment] 2018-08-23 13:38
@kdvolder just to let you know: @jrieken and I discussed that and we will propose a solution to the VS Code API that allows adopting this in the LSP so that white space sensitive languages get control over this. We will try to address this latest in the September milestone.

**Comment by jrieken** [comment] 2018-08-23 14:32
Idea would be to add something like `insertKind: CompletionItemInsertKind` with that being an enum with values like `Raw`, `AdjustWhitespace`, `FormatOnInsert` etc. The current default is to adjust whitespace wrt the insert location

**Comment by rcjsuen** [comment] 2018-10-16 13:03
Not totally related but I thought I'd bring up Microsoft/monaco-editor#1085 where someone raised a comment about the auto-indentation system in Mcrosoft's Monaco Editor.

**Comment by dbaeumer** [comment] 2018-12-20 11:58
@kvolder I was looking into this again and want to do the necessary changes and extension to the protocol to support the no formatting / formatting case. Here is what I would like to do:

- add a new field to the completion item to control this.
- if not present we would spec that the editor should adjust white space for multi line inserts. I think that makes server implementations easier since they don't need to worry about indentation in most cases.

Any insights, ideas ?

**Comment by kdvolder** [comment] 2018-12-20 16:53
@dbaeumer That would work for us. We would just have to make sure to include this 'disable the indenting' flag in all our completions, which is not hard.

**Comment by kdvolder** [comment] 2018-12-20 17:18
Want to add one small comment. So yes, your proposal is fine and something I can live with personally. All I really want is some way to disable the magic indents. But...

Perhaps the behavior of applying magic indents should really be 'opt in' not 'opt out'. Following the letter of the spec... 'opt-in' would make this really 'backwards compatible' and would make vscode behave the same as other clients that currently implement the spec. 

Making it 'opt-out' as you propose, is, technically speaking, not backwards compatible with the spec. Though it is backwards compatible with vscode.

Taking the 'opt-out' route would seem to be a choice that favors backwards compatibility with vscode versus backwards compatibility with all other clients.

Yes, making it opt-in is a 'breaking' change for vscode. But making it opt-out, is a breaking change for all other clients who did not implement magic indent, because it isn't in the spec.

Anyhoo... personally, I am fine with 'opt-in' or 'opt-out' because we can easily deal with it in our language servers either way. So practically speaking it matters little to me.

If I wanted to stand firmly on principle however, then I'd say that magic-indent should really be a 'opt-in' feature. As the saying goes though, we shouldn't make 'the perfect be the enemy of the good'. So let me be clear that I'm also prefectly happy to accept your proposal as the most practical way forward to get this issue resolved.

**Comment by puremourning** [comment] 2018-12-21 10:22
I thought the spec said that completion items may not contain newlines:

Spec:
> 	 * *Note:* The range of the edit must be a single line 

Completion items with newlines in them seem like strange idea that probably fall outside of the "completion" workflow.

Implementing indent in a LSP client for a completion item is a big and complex piece of work for a highly dubious use case imo. For example, in Vim it requires working strictly against Vim's completion system.

I think anything with newlines should be a workspaceEdit.

**Comment by dbaeumer** [comment] 2018-12-21 10:56
@puremourning thanks for getting back. That is true but the insert text can have newlines. Otherwise most snippets would be forbidden.

Can you elaborate more on this:

> Implementing indent in a LSP client for a completion item is a big and complex piece of work for a highly dubious use case imo. For example, in Vim it requires working strictly against Vim's completion system.

How does the Vim client handle snippets which for example insert a for loop like this. 

![capture](https://user-images.githubusercontent.com/1931590/50339321-7feaed00-0517-11e9-85c8-fecbae305b62.png)


Will it not insert them

**Comment by puremourning** [comment] 2018-12-21 17:00
Most vim clients probably don’t support snippet insertion. But if they do it would have to be as a bolt-on that happened outside of the completion system. Completion strings in vim may not contain new lines. Wel, they can but Vim inserts `^@` in their place. 

I tied to do this in ycmd but it is a real pain.

**Comment by mickaelistria** [comment] 2019-01-02 16:20
@dbaeumer I agree handling of auto-indent must be spec'd and that we can find a clarification without adding a capability nor extra types nor even an opt-in/out strategy. I think it's more than a single item to spec if we want to support most cases.

If we want spec that auto-indent is applied by default (opt-out), we should spec that:
1. When text edit is multiple lines, the client must repeat the indentation of the first line when completion item is applied to all new lines
2. '\b' means removing a level of indentation (can be a space or a tab)
3. clients are free to change the line-ending and to replace '\t' indent characters by combination of spaces.

If we want to spec auto-indent is off by default (opt-in), we should spec that:
1. When text edit is multiple line, not extra-character is expected to be added as indentation of new lines
2. Clients are free to change the line-ending and to replace '\t' indent characters by combination of spaces.

**Comment by kiennq** [comment] 2020-07-20 01:51
@dbaeumer Is there any news on this? Applying auto indentation can sometimes be really slow in some editor (like Emacs with `org-mode`) so I wonder if we can have a more simpler indentation that language server expect client to insert.
Doing magic indentation on client side may have side effect of what's expected format by client and server may not be in sync, so a `textDocument/rangeFormatting` can completely overwrite spaces/tabs in the text edit buffer.

I saw [this](https://github.com/microsoft/vscode/issues/57093) propose in VsCode  that [mentions ](https://github.com/Microsoft/vscode/blob/25589f6cc4aa3450450fa0f49979fcf7835f52d4/src/vs/vscode.proposed.d.ts#L16-L39)
``` ts
/**
 * Keep whitespace as is. By default, the editor adjusts leading
 * whitespace of new lines so that they match the indentation of
 * the line for which the item is accepeted.
*/
```
so the editor side indentation should be changing the leading whitespace of new lines to match with the line where item is accepted?

**Comment by dbaeumer** [comment] 2020-07-22 09:39
It got added to VS Code as a boolean (https://github.com/microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3870). Adopting the boolean would be straight forward and I think specing the behavior as well. Things get more complicated if we want to support the `\b` and `\t` as suggested here https://github.com/microsoft/language-server-protocol/issues/83#issuecomment-450908260. IMO this wouldn't be necessary since the server could always provide the right indentation.

**Comment by kdvolder** [comment] 2020-07-23 17:06
> Things get more complicated if we want to support the \b and \t as suggested here #83 (comment). IMO this wouldn't be necessary since the server could always provide the right indentation.

I agree. I think I may at some point have planted the idea of using `\b` as a negative indent signal. It is something I did try out (and it didn't work :-). However the only reason I tried to use `\b` in this way was because there was no way to disable the magic indents. If magic indents would be disabled then I wouldn't have any need to express a 'negative indent' relative to the magic indentation level.

**Comment by dbaeumer** [comment] 2020-11-06 13:08
I addressed this in the following way:

- the client announces now a `insertTextMode` in the completion client capabilities. Currently support are `asIs` and `adjustIndentation`. This value signals the default behavior of the client
- a completion item can have a `insertTextMode` property to overwrite a default client behavior if supported by the client. The support is signaled by the client capability `completionItem.insertTextModeSupport`

**Closed** 2020-11-06 13:09 UTC
Labels: clarification

**Comment by rwols** [comment] 2020-11-06 13:17
I would actually argue against having newlines in completion text edits. It just doesn't come across as very intuitive to me. The most natural completions are the ones that are shortest.

It's also not clear to the user whether selecting e.g. a completion of type "function" would now result in additional newlines or not. It makes the process of completing somewhat unpredictable.

**Comment by puremourning** [comment] 2020-11-06 14:41
> I would actually argue against having newlines in completion text edits. It just doesn't come across as very intuitive to me. The most natural completions are the ones that are shortest.

Agree, completions shouldn't contain newlines, because what gets inserted doesn't match what's shown in the menu, which is highly confusing.

Alas, we are where we are with this one. In the client, we just have to filter out completions with suggestions containing newlines.

**Comment by kdvolder** [comment] 2020-11-06 17:32
> Agree, completions shouldn't contain newlines, because what gets inserted doesn't match what's shown in the menu, which is highly confusing.

I completely disagree.

You are entitled to your opinion of course, and I'd say you are free not to create such completions in your language server, if you are making one.  I think this kind of choice should not be forced onto a server by the protocol or the client. The protocol / client should instead empower server authors to make this decision as it makes sense to them for their specific language.

BTW: 'Snippet / template proposals' are naturally multi-lined snippets of text and they are i.m.o a very useful type of completion. 

> The most natural completions are the ones that are shortest.

I question that. I don't know what it means to be 'natural'. However when talking about usefulness, e.g. in terms of how much a completion helps me as user by avoiding writing out small or larger bits of code manually... clearly the more useful completions are the larger ones.

That is precisely why multi-line 'snippet' completions are so useful in practice because they can insert larger templates of boilerplate code that would be rather laborious to type out in full by hand (or even when aided by many little completion steps invoked repeatedly).

**Comment by mickaelistria** [comment] 2020-11-06 17:44
I totally support @kdvolder here. In Eclipse IDE, we have plenty completion proposals that spans across multiple line, respect style and so on, basically bootstrapping some skeletons of relatively complex code that are "natural"  to place as such location in such context. If you remove such features from Eclipse IDE for Java, it would suddenly seem seems much weaker than it is now.
I expect that more languages may like to take advantage of it; and that any decent editor should be capable of properly handling multi-line text insertions/completions.
In any case, the fact that there is at least 1 serious and mature use-case for multi-line completion/text edits is enough to not try to dodge this issue, and instead to focus on finding a decent solution. To me, pretending insertions should be single-line is just a way to put some extra constraint to find a "cheaper" solution on short term and delay a bigger effort later trying to get rid of the constraint); not really a way to find the best solution.

**Comment by puremourning** [comment] 2020-11-06 18:40
> BTW: 'Snippet / template proposals' are naturally multi-lined snippets of text and they are i.m.o a very useful type of completion.

I agree that these are useful in, but I'm sort of of the _opinion_ that it feels awkward in an auto-completion menu. feels like the kind of thing that lives in a different client-gesture (like 'expand snippet' or a code-action type thing). 

Taking the one I know, jdt.ls returns a completion item with the menu text of `get` which creates a getter method when selected. It's kind of jarring when all other completions in the same menu just essentially insert the text selected. 

As you say, opinions clearly differ on this.

And like I said, the cat's out of the bag; servers are already doing this, and I 100% agree that the semantics and the bahaviours associated should be prescribed such that client authors like myself don't have to parse the vscode source code to find out what the de facto behaviour should be. I'm not completely convinced that the `insertTextMode` does that, but it's certainly a good signal.

Perhaps servers could be encouraged _not_ to send multi-line suggestions when clients don't advertise support for `adjustIndentation` client capability. Though I fear this is a forlorn hope.

**Comment by kdvolder** [comment] 2020-11-10 18:41
@dbaeumer The wording on how magic indents are applied/defined/computed is a bit too vague i.m.o. For example if you scrolled way up there is this question for clarification I raised:

https://github.com/microsoft/language-server-protocol/issues/83#issuecomment-272506633

There are probably different cases to consider depending on where the cursor is w.r.t to the line into which we are inserting/applying an edit. If you don't want to have clients doing each something slightly different, then it probably needs to be specific explicitly.

**Comment by kdvolder** [comment] 2020-11-10 18:43
> As you say, opinions clearly differ on this.

Agreed, and that is exactly why the client/protocol should not force this choice onto a server implementor.

**Comment by dbaeumer** [comment] 2020-11-11 09:24
@kdvolder clarified it. I speced it to use 3 spaces taking your example since this is what I as a user would expect to happen.

**Comment by kdvolder** [comment] 2020-11-12 19:25
Okay so that clarifies it for the situation where cursor is inside the leading whitespace. But what about the case when it is not? The wording we had before seemed more applicable/specific to that, whereas the new wording now is clear for when the cursor is preceded by only white spaces, but I think it is now ambiguous when the cursor is at the end of or in the middle of a non-whitespace area.

So specifically, for this example:
```
    some<*>
```

What is the meaning of 'indentation upto the cursor'? I can think of two possible interpretations. One gives 7 (3 spaces + 2 letters) and the other gives 3. I'm pretty sure (?) that you want the result to be 4 (i.e. counting only whitespace) but I do not think that is totally clear from the wording.

Another potentially confusing issue is whether the magic indent are really applied relative to the 'cursor' or rather whether is based on the insertion position of a text edit. (I beleave vscode probably uses the positions in the edit as queues for computing the magic indents, not the place the cursor was in, though we may expect these to be somewhat related. Nevertheless, language server produces these edits and so they are really independent of the cursor position that client keeps track of.

So I think where the word 'cursor' is used now in the description, it probably actually means 'insertion position' (which is the same as cursor position in many/most cases but not necessarily all cases).

**Comment by kdvolder** [comment] 2020-11-12 19:45
I suggest some very specific wording like:

> The editor adjusts leading whitespace of new lines, by copying exactly the leading whitespace on the line to which the edit is applied, upto the edit's starting postion (for a text edit) or the insertion position (for insertions).
