### ISSUE TITLE
Spec clarification: data type 'unknown' vs 'any'

### ISSUE THREAD

**Issue by ulugbekna** [microsoft/language-server-protocol#1242] opened 2021-04-09 07:49 UTC
I wonder what's the difference between 'unknown' data type and 'any'.

Example:

For `CompletionItem`: 

```ts
...
         /**
	 * A data entry field that is preserved on a completion item between
	 * a completion and a completion resolve request.
	 */
	data?: any;
...
```

For `Diagnostic`:

```ts
...
        /**
	 * A data entry field that is preserved between a
	 * `textDocument/publishDiagnostics` notification and
	 * `textDocument/codeAction` request.
	 *
	 * @since 3.16.0
	 */
	data?: unknown;
...
```

**Comment by KamasamaK** [comment] 2021-04-09 08:08
Duplicate of #1235

In the context of the spec, there is nothing different. These are top types in TypeScript.

**Comment by dbaeumer** [comment] 2021-04-09 09:32
Dups #1235.

**Closed by dbaeumer** 2021-04-09 09:32 UTC
