### ISSUE TITLE
Should filterText trim prefixes?

### ISSUE THREAD

**Issue by stamblerre** [Microsoft/language-server-protocol#729] opened 2019-04-20 19:26 UTC
For example, if I have a variable `abc` in scope, and I have typed `a`, should the filter text be `bc`? I would guess yes, based on the behavior of VSCode, but it seems that other language servers behave differently.

For context, this question was first brought up in https://github.com/golang/go/issues/31552 and https://github.com/tigersoldier/company-lsp/issues/103.

**Comment by rcjsuen** [comment] 2019-04-20 20:16
Personally, I don't trim `filterText` in my language server but I can't speak for anyone else. I don't recall any past discussions about this field either.

**Comment by stamblerre** [comment] 2019-04-22 19:23
It seems that most other language servers don't either, and I didn't expect that I had to - however, without doing trimming, VSCode doesn't behave as I would expect it to. Perhaps this is a VSCode bug? Would be happy to file it there, but it would also be helpful to clarify this in the spec.

**Comment by muirrn** [comment] 2019-04-24 17:11
The Rust server does not set `filterPrefix` but works correctly in VSCode (using the example in https://github.com/golang/go/issues/31552#issuecomment-485155150). This is starting to look like a VSCode go extension bug. Do language extensions have custom handling of completion candidates?

**Comment by stamblerre** [comment] 2019-04-24 17:43
The only handling would be in the language client, which is in https://github.com/Microsoft/vscode-languageserver-node. I'll open an issue there, but for now, I'll leave the filter text as is in `gopls`. Maybe I can add a temporary config to not trim it.

**Comment by dbaeumer** [comment] 2019-04-25 09:36
@stamblerre I commented in https://github.com/Microsoft/vscode-languageserver-node/issues/488

Lets close this issue for now until I have a better understanding why your case is failing. I was not able to reproduce it.

**Closed by dbaeumer** 2019-04-25 09:36 UTC
