### ISSUE TITLE
Feature: Inlay Hints

### ISSUE THREAD

**Issue by kjeremy** [microsoft/language-server-protocol#956] opened 2020-04-08 14:41 UTC
I would like to upstream rust-analyzer's inlay hints feature. This allows an editor to place annotations inline with text to display parameter names, type hints etc.

See: https://github.com/microsoft/vscode-languageserver-node/pull/609 for the proposal.

**Comment by rcjsuen** [comment] 2020-04-08 15:03
```JavaScript
var someNumber = 123;
```
@kjeremy Given the above JavaScript code, the `range` in the returned `InlayHint` would be `{ start: { line: 0, position 4 }, end: { 0, position: 14 } }` so that it encompasses the `someNumber` variable, correct?

Can you provide examples of a parameter hint and a chaining hint?

**Comment by Veetaha** [comment] 2020-04-08 18:02
What we do in `rust-analyzer` is:
1. Send a request `rust-analyzer/inlayHints` on any source change (i.e. any character typed, any file moved/created/deleted etc.).
2. As a parameter we pass `{ textDocument: TextDocumentIdentifier }` for the particular file we need to get inlay hints for.
3. The server responds with an array of `InlayHint` objects for the requested file.

Here is a simplified, *stringly-typed* version of it ([we use a discriminated union at our repo instead](https://github.com/rust-analyzer/rust-analyzer/blob/4762c6d9c66dc1b6be9b9010dbe787ef8d69530a/editors/code/src/rust-analyzer-api.ts#L91-L108)):
```ts
import * as lc from "vscode-languageclient";

export interface InlayHint {
    range: lc.Range;
    label: string;
    kind: string;
}

export interface InlayHintsParams {
    textDocument: lc.TextDocumentIdentifier;
}

const inlayHints = new lc.RequestType<InlayHintsParams, InlayHint[], unknown>(
    "rust-analyzer/inlayHints"
);
```
[The client-side implementation for this feature is very straight-forward and actually fits into < 250 lines of code](https://github.com/rust-analyzer/rust-analyzer/blob/master/editors/code/src/inlay_hints.ts). It currently uses the vscode text decorations feature (more precise inlay hints are `after` and `before` css pseudoelements), but this feature is **very limited**.
Current limitations:
1. It feels unnatural when the cursor goes through the inlay hint, it's hard to describe it better be seen:
![inlays_limitations](https://user-images.githubusercontent.com/36276403/78813846-512bab00-79d6-11ea-89c7-d0f587da72f0.gif)
The cursor kind jumps through the hint and the nearby token. IntelliJ in this case emulates the inlay hint being a real holistic token in the editor.
2. As you can see on the *.gif* these `after` and `before` pseudoelements inherit the styling from the token they are attached to. This means whenever that token (e.g. the variable name, a paren, a coma etc.) changes its style (e.g. is highlighted, outlined, etc) the inlay hint changes its style along with it, which is unwanted...
3. Text decorations don't let you tweak too much of their style. For example, we cannot change their font size to make them a bit smaller and vertically center them in the middle of the line of code.

Our current implementation can be very easily generalized and integrated into LSP:
1. The inlay hint `kind` should not be a fixed enum (I propose to change it in this PR @kjeremy), but just some string identifier for which the user can customize display styling. This gives lsp server developers the flexibility to add new kinds of inlay hints they can that think of without changing the protocol, and the editor should be abstract and not provide any ad hoc implementation (but we might consider the protocol to specify the `well-known` inlay hint kinds where special support for them may be implemented (e.g. by clicking on the type hint the editor invokes goto-definition of the type, or by clicking on the parameter name hint it invokes goto-definition of the parameter on the function that is invoked, etc.)
2. The server itself should decide to which token and on **which side** (after/before) of the token the editor should place the inlay hint. So we might modify the `InlayHint` interface:
    ```ts
    interface InlayHint {
        range: lc.Range;
        kind: string;
        label: string;
        position: "after" | "before";
    }
    ```
3. The strategy for invalidating the inlay hints should also be tweakable. For example, the server should register the inlay hints capability with the following options for invalidation.
Just a naive scratch of invalidation events:
    ```ts
    enum InlayHintsInvalidationEvents {
        TextDocumentContentChanged = 0b0001,
        WorkspaceFileRemoved = 0b0010,
        WorkspaceFileAdded = 0b0100,
        WorkspaceFileMoved = 0b1000
    }  
    ```

So this describes the pull-based implementation of inlay hints that is currently used at `rust-analyzer`.
We might think of a push-based implementation instead, where the server can decide whether inlay hints are invalidated or not, but I guess we cannot easily implement it via only LSP protocol right now, this might require some more changes to the protocol to let the server always know which text documents are opened in the editor at any point of time.

Maybe @matklad  can elaborate on Intelij where they've natively implemented this feature and which model/API they've considered best to be used.a

**Comment by Veetaha** [comment] 2020-04-08 18:14
@rcjsuen the chaining hint is a type hint that is displayed after each chain of the multiline method call.
<details>

<summary>Example</summary>

![image](https://user-images.githubusercontent.com/36276403/78818791-e54d4080-79dd-11ea-89e7-9b634fa6a6f9.png)

</details>

**Comment by Trass3r** [comment] 2020-07-10 14:57
Linking this to https://github.com/microsoft/vscode/issues/16221.

**Comment by mickaelistria** [comment] 2020-07-10 15:02
Isn't it a dup of #405 ?

**Comment by Trass3r** [comment] 2020-07-10 15:06
Well this one is an actual LSP extension proposal, not just a feature request.

**Comment by mickaelistria** [comment] 2020-07-10 15:12
And isn't it also a dup of #745 ?
The current proposal seems quite complex to me while the protocol seems to already have something very similar that can be enriched.

**Comment by matklad** [comment] 2020-07-10 15:33
Yup, seems like there are at least four threads of discussion about LSP:

* #956 (this)
* #745 
* #405 
* microsoft/vscode-languageserver-node#609

+ microsoft/vscode#16221 (vscode support)

It makes sense to do some issue garbage collection at least :-)

**Comment by matklad** [comment] 2020-07-10 15:36
Enhancing code lens request seems fine by me! We need to:

* add a `label` so text can be drawn without command
* add a `render_position: 'above' | 'before' | 'after' | 'lineEnd'` to control where, relative to the range, the annotation should be rendered
* add a `kind` such that the client can, eg, show parameter hints but not type hints.

**Comment by mickaelistria** [comment] 2020-07-10 15:41
> add a label so text can be drawn without command

+1

> add a render_position: 'above' | 'before' | 'after' | 'lineEnd' to control where, relative to the range, the annotation should be rendered

I think we only need "above" and "before". "after" is actually "before" the next character; "lineEnd" is before line break. For the case of the lineEnd or the last line, we can just say that if position reaches file end, it's the lineEnd of last line.

> add a kind such that the client can, eg, show parameter hints but not type hints.

I don't think filtering should happen on client side. Instead, clients should send "didChangeConfiguration" request to inform the LS about which annotations it's interested in, so the LS can then avoid some useless computation and send smaller messages.

**Comment by HighCommander4** [comment] 2020-07-10 15:47
If this is shoehorned into code lens, it would be really good for the user to have a way to configure, that only this kind of code lens is shown. For example, I find that `render_position: above` code lens breaks the vertical spacing of lines and would prefer to never show those.

**Comment by matklad** [comment] 2020-07-10 16:02
>I think we only need "above" and "before". "after" is actually "before" the next character;

So I think there are two ways we can spin this. *First*, the `range` might mean "where to draw the annotation", and then indeed we don't need many positions. We don't need the `range` even, as we only need to point to a single position between chars. *Second*, the `range` might be semantic (the piece of source code that is being annotated), and then we do need position to specify where we render the annotation, relative to the bit of code. 

I lean towards the second approach, as it unlocks interesting possibilities (for example, the client can render the annotation only when the cursor is on an annotate element) and just seems  more proper, as it doesn't encode to fine representation details into the protocol.

>I don't think filtering should happen on client side. Instead, clients should send "didChangeConfiguration" request to inform the LS about which annotations it's interested in, so the LS can then avoid some useless computation and send smaller messages.

Leaning on the server-specific configuration would prevent users from enabling/disabling parameter hints for all languages with a single config. I feel we should do the same pattern we use for code actions -- client & server negotiate supported kinds, and then client can send `only` in the request. This still allows server to save some work. 

More generally, while implemented the server I've noticed that it generally is a good idea to just pass configuration as a parameter to request, instead of relying on some ambient *state*. This is primarily because state makes *everything* painful, but I also see concrete tangible benefits with per-request filtering. For example, one of the biggest problem with inlay hints is that they are "annoying". I can imagine a client implementing "flash hits" action, which would show all hints momentarily, and dismiss them afterwards. With `only`, the client only needs to request all the hints at a point in time. With config, the client needs to set config, send a request, and reset config back (possible interfering with requests for other files).

**Comment by sam-mccall** [comment] 2021-04-13 10:26
VSCode has a proposed API for this now: https://github.com/microsoft/vscode/blob/main/src/vs/vscode.proposed.d.ts. @dbaeumer does this mean anything for the timeline of having this in LSP?

@HighCommander4 is working on this for clangd in https://reviews.llvm.org/D98748, mostly following the rust-analyzer protocol. Our hope is to converge with whatever gets standardized.

---

Range is different between the two models:
 - The VSCode API seems to use "range" to mean "which text to replace with the hint", which would often be empty. Being able to do this seems useful: e.g. in C++ we may want to replace `auto` with the concrete type, or have parameter hints replace hand-written annotations like `foo(/*bar=*/42)`
 -  The rust-analyzer API uses "range" to mean "which text the annotation applies to". This seems useful too! (@matklad's arguments above)

You could accommodate both by using rust-analyzer's `range`, adding `position = "before"|"after"|"overwrite"`. (The "above" and "lineEnd" values described above aren't in VSCode currently)

---

It seems like it'd be useful at some point to be able to "target" these for code actions (like diagnostics). In particular, to be able to make some deduced info explicit in the source code (spell out deduced types, annotate parameter names). But this seems like something that can reasonably be bolted on later.

**Comment by dbaeumer** [comment] 2021-04-14 11:54
@sam-mccall @matklad since you have experiences with this would you be willing working on a PR that brings this to LSP and vscode-languageserver-node? That would be the fastest to make progress on this :-)

**Comment by matklad** [comment] 2021-04-14 12:02
cc @SomeoneToIgnore, they implemented this on our side.

**Comment by SomeoneToIgnore** [comment] 2021-04-14 12:19
I'm afraid I cannot allocate enough time to compose the whole PR myself in the next few months, but I'll put a reminder to reassert the situation in July and start working on it if nobody takes it over before.

Meanwhile, I'm more than glad to help with reviewing, discussing or trying out any related code on r-a codebase.
I already have a branch in r-a and a set of instructions: https://github.com/rust-analyzer/rust-analyzer/issues/2797#issuecomment-811902058 that should be enough to check against any updates to the API in question.

If you want to reach me, feel free to use any contacts from my GitHub profile on [Zulip](https://rust-lang.zulipchat.com/#narrow/pm-with/231447-user231447)

**Comment by sam-mccall** [comment] 2021-04-20 16:42
I think I can give this a try. I'd approach this in order:

 - protocol/spec text (try to resolve various ideas discussed here and in related issues)
 - VSCode client support (make sure it works, test against existing servers)
 - VSCode server support (I guess this is pretty mechanical, but also I haven't seen this code)

I guess they should all land together, but probably can get some meaningful review after each stage.

(sorry about the delay, managed to free up some capacity)

**Comment by sam-mccall** [comment] 2021-04-20 17:14
One thing I haven't seen mentioned: reducing the amount of data sent over the wire.

There seem likely to be a lot of these hints (e.g. one for each parameter passed to a function). And fully describing a hint could be a fair amount of data (text, range, positioning info, kind, ...). We could consider techniques inspired by semantic tokens to reduce it:

 - optional range-restricted retrieval, which VSCode's proposed API supports. 
 - factoring out position + kind + ... into a "class" defined at initialization
 - some sort of compact numeric encoding like semantic tokens uses
 - some sort of delta request

Semantic tokens does all of these, some large-ish requests like Outline do none of them :-)

**Comment by sam-mccall** [comment] 2021-04-20 21:24
I've added a first attempt in #1249 - spec text only, with a few open questions.

**Comment by dbaeumer** [comment] 2021-04-21 09:20
@sam-mccall thanks! will have a look.

**Comment by DanTup** [comment] 2021-05-08 14:25
Would this feature be able to support VS Code's new "Inline Value provider" API too (eg. the returned hints could be a variable name or evaluation expression, and would be mapped into an `InlineValuesProvider` to be rendered only during debugging), or would that need to be implemented seperately?

https://code.visualstudio.com/updates/v1_54#_inline-value-provider-api

**Comment by DanTup** [comment] 2021-05-19 11:13
@dbaeumer any thoughts on the above? Should it be part of or separate to this?

**Comment by dbaeumer** [comment] 2021-05-19 13:12
@DanTup IMO this should be separate since it is more a debugger feature not a language feature.

**Comment by DanTup** [comment] 2021-05-19 13:17
@dbaeumer I wasn't sure if the VS Code implementation was intended to be more generic (since it supports multiple types of inlays, including `InlineValueText` which - if I understand correctly - is unrelated to debugging?). If they shouldn't be combined though, I'm happy to start a PT for adding a `textDocument/inlineValues` or similar based on the VS API.

**Comment by dbaeumer** [comment] 2021-05-19 13:56
Could you explain what a language server would provide here?

**Comment by DanTup** [comment] 2021-05-19 14:17
@dbaeumer I'm trying to implement inline debugger values. My understanding of [this new API (vscode.languages.registerInlineValuesProvider)](https://code.visualstudio.com/updates/v1_54#_inline-value-provider-api) is that it's now a language feature to supply ranges in a document and their variable names (or expressions) that can be used during a debugging session to render their inline values?

**Comment by DanTup** [comment] 2021-06-14 10:01
@dbaeumer does the above make sense? VS Code's inline values seems to have been designed as a language feature and it feels like there's a lot of overlap with this.

**Comment by KamasamaK** [comment] 2021-07-14 17:41
@DanTup Even if you feel there's a lot of overlap, it's still a separate feature, so please create a separate issue. This issue corresponds to the [proposed VS Code API for Inlay Hints](https://github.com/microsoft/vscode/blob/082f48c4f2656718a0ab64f1d1589d065101a19b/src/vs/vscode.proposed.d.ts#L1656) which is a separate VS Code API from the one you're talking about.

**Comment by DanTup** [comment] 2021-07-14 17:47
I'm happy to do that, but it seems like that feature would be a superset of this one so I wanted some confirmation that really made sense (it seems strange to ultimately have two overlapping APIs where servers and clients have to pick between, or implement two).

(I'm also slightly unsure based on @dbaeumer's comments above whether it would be accepted here.. I don't know if my understanding of the feature is correct - that is, this uses the language server to mark up ranges that could be used during debugging).

**Comment by DanTup** [comment] 2021-07-20 10:21
I've filed a separate PR to discuss inlineValues:

https://github.com/microsoft/language-server-protocol/pull/1318

I previously misread @KamasamaK's comment above and didn't realise that VS Code also had both APIs. I'm not sure I completely understand why one isn't built on the other (both seem to be similarly generically named and to do similar things), but I suspect there are reasons if it's the route VS Code took so mirroring that here makes more sense to me now.

**Comment by kitsonk** [comment] 2021-09-03 02:56
InlayHints have shipped in stable vscode and are integrated into for TypeScript/JavaScript (although the API is still _proposed_).  It would make sense to add that version of inlay hints to the specification?

**Comment by dbaeumer** [comment] 2021-09-03 08:25
Agree, a PR always helps to speed things up :-)

**Comment by kitsonk** [comment] 2021-09-03 09:45
I will try to raise one in a little bit, I assume to the 3.17 doc in the gh_pages?

**Comment by kitsonk** [comment] 2021-09-03 12:01
Hopefully #1339 will speed things up.

**Comment by KamasamaK** [comment] 2022-03-04 13:03
VS Code has shipped with a [finalized API](https://github.com/microsoft/vscode/blob/778b74a2159983ba09568d069ef9c9ecd858f783/src/vscode-dts/vscode.d.ts#L4570-L4732) for this.

**Comment by KamasamaK** [comment] 2022-04-06 18:26
@dbaeumer This is missing the 3.17 milestone

**Comment by dbaeumer** [comment] 2022-04-07 06:32
Correct and closing.

**Closed by dbaeumer** 2022-04-07 06:32 UTC
Labels: feature-request, new request

**Comment by DanTup** [comment] 2022-06-13 17:22
After waiting a while for this, I was disappointed to find (and surprised that I'd missed it before) the `Kind`s here are quite restrictive (type/parameter names). I'd been hoping to use it for these labels we show in Dart (to help relate closing parens to where they're opened):

![image](https://user-images.githubusercontent.com/1078012/173409059-fa72702b-574f-4a83-8668-31149d784c59.png)

Currently they're rendered using Decorations and custom messages from the LSP server, but I'd really like them to be something standard so other clients can use them without implementing custom messages (something that's unlikely to happen in editors that don't have a specific language extension and only generic LSP support).

I've filed an issue with VS Code - if anyone else was planning to use them for something more generic, please consider adding 👍 !

https://github.com/microsoft/vscode/issues/151920

**Comment by thaliaarchi** [comment] 2022-06-13 18:29
Like @DanTup, I find the `InlayHintKind` values restrictive for my use case. I am building a language server for Whitespace that will display the opcodes inline in the invisible code, to make editing easier. These aren't type or parameter annotations, but rather display the statements in an alternate syntax.

For example, here is roughly what a program would look like with the inlay hints interspersed:

```whitespace
push·1   	
label·C
   	    		
dup 
 printi	
 	push·10   	 	 
printc	
  push·1   	
add	   dup 
 push·11   	 		
sub	  	jz·E
	  	   	 	
jmp·C
 
 	    		
label·E
   	   	 	
drop 

end


```

I've also written a little more about it in [a gist](https://gist.github.com/andrewarchi/79bef21ba2bad83a256477ed74eadf0f), which includes this program in the standard syntax, assembly syntax, and with inlay hints.

**Comment by matklad** [comment] 2022-06-14 08:19
@DanTup note that you don't have to use custom decorators to do that, it's possible to achieve this using today's inlay hints API. `rust-analyzer` does this. We send kind to `null` for all custom kinds of inlays: 

https://github.com/rust-lang/rust-analyzer/blob/7db73875ac0d9280ae93b14232249d9c1496583a/crates/rust-analyzer/src/to_proto.rs#L472

**Comment by DanTup** [comment] 2022-06-14 08:46
@matklad the decorations is the old implementation from before InlayHints. I wanted to migrate it to Inlay Hints. The wording of the kind suggests that the editor might assume type/param names of `kind` isn't provided, so the theming could be confusing:

> Can be omitted in which case the client should fall back to a reasonable default.

Telling users to modify some "parameter names" color or similar to control this would be odd.

In the past I've shipped things that didn't line up with the spec and things have changed/been broken, so I'm trying to avoid using things for purposes they might not be intended for (at least without some reasonable clarification that it's a valid use).

**Comment by jasonjurotich** [comment] 2022-11-17 22:04
Just wanted to know if there was any advances in the inlay hints in Helix. It's the only think keeping me from moving from VSCode...

**Comment by poliorcetics** [comment] 2023-02-11 12:17
If there are two inlay hints request in flight for two different files, I see no way in the returned `InlayHint` data to see for which URI they apply (https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_inlayHint), do I just hope the last-response is to be used for the currently focused file ?

**Comment by sam-mccall** [comment] 2023-02-11 12:21
@poliorcetics the client request specifies which document it is for and specifies a request ID. The server response includes the request ID it corresponds to. This applies to all request/response pairs.

Edit: this isn't described in each request/response message in the spec as it's part of the JSON-RPC layer that encloses them.
