### ISSUE TITLE
Feature request: project-level diagnosis errors

### ISSUE THREAD

**Issue by chenglou** [Microsoft/language-server-protocol#305] opened 2017-09-23 00:56 UTC
I might be mistaken, but seeing https://github.com/Microsoft/language-server-protocol/blob/30cd9e13bfb68ecd711837482b92eda1c65b5ab2/protocol.md#publishdiagnostics-notification, it seems that we cannot define an error that doesn't belong to a file? The use-case is for reporting errors like "your build configuration is wrong" or "some dependencies aren't installed correctly". 

cc @jchavarri

**Comment by smarter** [comment] 2017-09-23 13:45
Duplicate of https://github.com/Microsoft/language-server-protocol/issues/256

**Comment by dbaeumer** [comment] 2017-10-03 09:07
Yes, dups #256.

**Closed by dbaeumer** 2017-10-03 09:07 UTC
Labels: duplicate
