### ISSUE TITLE
Server stubs for various languages

### ISSUE THREAD

**Issue by owlbit** [Microsoft/language-server-protocol#99] opened 2016-10-20 12:54 UTC
Right now there are several language servers implemented in a variety of languages: Rust, Go, C++ etc. However these servers are often closely coupled to the language they are serving, and so not reusable without some effort.
A possible solution is to provide server stubs (similar to how [swagger](http://swagger.io/) does, say) in a variety of languages (Node, Go, etc.) allowing the same language server framework to be used to target multiple languages.
As an example, you would have a Node server stub implementation that could be used as a starting point for a language server serving Rust, but also Java. This would help to minimize reinvention of the wheel and would encourage others to start writing servers in the language of their choice, without writing the boilerplate.

**Comment by dbaeumer** [comment] 2016-10-31 14:12
The node language server is available here: https://github.com/Microsoft/vscode-languageserver-node

**Comment by bruno-medeiros** [comment] 2016-11-01 11:07
> As an example, you would have a Node server stub implementation that could be used as a starting point for a language server serving Rust, but also Java.

The problem is, very rarely you will find people wanting to working an language server written on one language, but targetting another. The exceptions would be if the languages are very similar or closely related (say Java and other JVM languages like Groovy/Scala), or if the target language is deemed too slow to write a language server (so say, a Ruby LS could be written in Go or some other compiled language to be faster).

The other way around, from a low-level language to a higher-level one (like a Rust or Go LS written in Node), is very unlikely... (speaking from experience BTW: I wrote one such engine targetting D, written in Java, and over years never got much interest, in terms of contributions. The feedback I got is D developers didn't like Java, so would rather contribute in D only)

The other exception I can think of, is if you have a cross-language engine framework, like IntelliJ's Platform SDK.

But, it any case, does any of this matter to LSP? All of the above is LSP agnostic...

**Comment by dbaeumer** [comment] 2017-11-24 14:48
To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we’re happy to listen and to reconsider.

**Closed by dbaeumer** 2017-11-24 14:48 UTC
Labels: discussion
