### ISSUE TITLE
Escape characters in insertText

### ISSUE THREAD

**Issue by mickaelistria** [Microsoft/language-server-protocol#232] opened 2017-05-03 13:43 UTC
From a completion request in JSon, using VSCode language server for JSon, I receive the following completion item:

```json
{
  "jsonrpc": "2.0",
  "id": "4",
  "result": {
    "label": "$schema",
    "kind": 10,
    "documentation": "",
    "filterText": "\"$schema\"",
    "insertText": "\"\\$schema\": $1",
    "insertTextFormat": 2,
    "textEdit": {
      "range": {
        "start": {
          "line": 8,
          "character": 4
        },
        "end": {
          "line": 8,
          "character": 4
        }
      },
      "newText": "\"\\$schema\": $1"
    }
  }
```

I'm using LSP4J Java client.
Note that the "newText" does have some strange escaping characters, especially the `\\` before `$schema`. LSP4E (Eclipse client) interprets it as a backslash to insert, however I imagine the idea is to not insert it there, is it?
If so, can you please clarify in the protocol documentation how strings are supposed to be escaped, additionally to the JSon conventions?

**Comment by dbaeumer** [comment] 2017-05-17 11:16
The insertTextFormat is set to 2 which indicates a snippet. The snippet support in LSP is based on TextMate snippets. If you want to have the `$` literal in it you need to escape it as `\$` which in a quoted string results in `\\$`

I am closing the issue since this is expected behavior.

**Closed by dbaeumer** 2017-05-17 11:16 UTC
